language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed # build feed
  - docker build -t udagram-api-user ./udagram-api-user # build user
  - docker build -t udagram-frontend ./udagram-frontend # build frontend
  - docker build -t reverseproxy ./reverseproxy # build reverseproxy
  - docker tag udagram-api-feed pabhilashlearn/udagram-api-feed:v1 # tag feed
  - docker tag udagram-api-user pabhilashlearn/udagram-api-user:v1 # tag user
  - docker tag udagram-frontend pabhilashlearn/udagram-frontend:v1 # tag frontend
  - docker tag reverseproxy pabhilashlearn/reverseproxy:v1 # tag feed

after_success:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pabhilashlearn/udagram-api-feed:v1
  - docker push pabhilashlearn/udagram-api-user:v1
  - docker push pabhilashlearn/udagram-frontend:v1
  - docker push pabhilashlearn/reverseproxy:v1